# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='flag',
        ),
        migrations.AddField(
            model_name='word',
            name='coef',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='isAdjective',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='word',
            name='isAdverb',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='word',
            name='isNoun',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='word',
            name='isVerb',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='word',
            name='meta',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_rus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
